# Internal CA setup for using our own Certificate Authority

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: internal-ca
spec:
  ca:
    secretName: internal-ca-key-pair  # This secret contains the CA key pair

---
# This secret would be populated with the CA certificate and private key
# from Genesis secrets (CA_PRIVATE_KEY and CA_CERTIFICATE)
apiVersion: v1
kind: Secret
metadata:
  name: internal-ca-key-pair
  namespace: cert-manager
type: kubernetes.io/tls
data:
  tls.crt: ${CA_CERTIFICATE}  # Base64-encoded CA certificate
  tls.key: ${CA_PRIVATE_KEY}  # Base64-encoded CA private key

---
# Create a ClusterIssuer to generate certificates across any namespace
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-ca-cert
  namespace: cert-manager
spec:
  isCA: true
  commonName: DND Nordic Internal CA
  secretName: internal-ca-cert
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer

---
# ConfigMap to distribute the CA certificate to all nodes
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-trust-bundle
  namespace: cert-manager
data:
  ca.crt: ${CA_CERTIFICATE_RAW}  # Non-base64 encoded CA certificate for trust stores

---
# DaemonSet to automatically install CA certificate on all nodes
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ca-trust-installer
  namespace: cert-manager
spec:
  selector:
    matchLabels:
      name: ca-trust-installer
  template:
    metadata:
      labels:
        name: ca-trust-installer
    spec:
      hostPID: true
      containers:
      - name: installer
        image: ubuntu:22.04
        securityContext:
          privileged: true
        command: ["sh", "-c"]
        args:
        - |
          # Install the CA certificate to the host's trust store
          cp /ca-cert/ca.crt /host/usr/local/share/ca-certificates/dndnordic-internal-ca.crt
          chroot /host update-ca-certificates
          echo "CA certificate installed in host trust store"
          
          # Add certificate to Java keystore for Java applications
          mkdir -p /host/etc/pki/ca-trust/extracted/java
          chroot /host bash -c "find / -name 'cacerts' -type f -path '*/lib/security/*' | while read -r keystore; do
            echo \"Adding CA certificate to Java keystore: \$keystore\"
            keytool -importcert -noprompt -keystore \"\$keystore\" -storepass changeit \
              -alias dndnordic-ca -file /usr/local/share/ca-certificates/dndnordic-internal-ca.crt || true
          done"
          
          # Also update Istio specific locations
          mkdir -p /host/etc/istio/root-cert
          cp /ca-cert/ca.crt /host/etc/istio/root-cert/root-cert.pem
          
          # Keep container running so we can verify or re-run if needed
          echo "CA certificate installation completed"
          sleep infinity
        volumeMounts:
        - name: ca-cert-volume
          mountPath: /ca-cert
        - name: host-root
          mountPath: /host
      volumes:
      - name: ca-cert-volume
        configMap:
          name: ca-trust-bundle
      - name: host-root
        hostPath:
          path: /
