# Gamma Cluster (Paris) - CA Configuration
# This is the third of the redundant CA deployments

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-gamma
  namespace: cert-manager
  labels:
    app: cert-manager
    cluster: gamma
    region: paris
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cert-manager
  template:
    metadata:
      labels:
        app: cert-manager
        cluster: gamma
    spec:
      # Similar to the main deployment, but with cluster-specific configuration
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - eu-west-3a
                - eu-west-3b
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: cert-manager
        image: quay.io/jetstack/cert-manager-controller:v1.12.0
        args:
        - --v=2
        - --cluster-resource-namespace=$(POD_NAMESPACE)
        - --leader-election-namespace=$(POD_NAMESPACE)
        - --cluster-name=gamma
        - --region=paris
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: gamma-config
          mountPath: /etc/config
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: gamma-config
        configMap:
          name: cert-manager-gamma-config

---
# Gamma cluster specific configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-gamma-config
  namespace: cert-manager
data:
  cluster.json: |
    {
      "cluster": {
        "name": "gamma",
        "region": "paris",
        "role": "backup",
        "primary": "alpha",
        "other_backup": "beta",
        "endpoints": {
          "alpha": "internal-alpha-api.origin.svc.cluster.local",
          "beta": "internal-beta-api.origin.svc.cluster.local"
        }
      }
    }
  issuers.json: |
    {
      "issuers": {
        "primary": "internal-ca",
        "backups": ["alpha-ca", "beta-ca"]
      }
    }

---
# Gamma cluster root CA reference
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gamma-ca
  namespace: cert-manager
spec:
  ca:
    secretName: internal-ca-key-pair