apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  serviceName: keycloak
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:latest
        args: ["start", "--optimized"]
        env:
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: keycloak-admin
              key: username
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-admin
              key: password
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL_HOST
          value: "keycloak-postgresql"
        - name: KC_DB_URL_PORT
          value: "5432"
        - name: KC_DB_URL_DATABASE
          value: "keycloak"
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: keycloak-postgresql
              key: username
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-postgresql
              key: password
        - name: KC_CACHE
          value: "ispn"
        - name: KC_CACHE_STACK
          value: "kubernetes"
        - name: KC_HTTP_RELATIVE_PATH
          value: "/auth"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_PROXY
          value: "edge"
        - name: JAVA_OPTS_APPEND
          value: >-
            -Djgroups.bind_addr=global
            -Djgroups.join_timeout=1000
            -Djboss.jgroups.azure_ping.storage_account_name=$(AZURE_STORAGE_ACCOUNT_NAME)
            -Djboss.jgroups.azure_ping.storage_access_key=$(AZURE_STORAGE_ACCESS_KEY)
            -Djboss.jgroups.azure_ping.container=$(AZURE_CONTAINER_NAME)
        - name: AZURE_STORAGE_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: azure-storage
              key: account-name
        - name: AZURE_STORAGE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: azure-storage
              key: access-key
        - name: AZURE_CONTAINER_NAME
          value: "keycloak-ping"
        ports:
        - name: http
          containerPort: 8080
        - name: jgroups
          containerPort: 7600
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: http
          initialDelaySeconds: 90
          timeoutSeconds: 4
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /auth/realms/master
            port: http
          initialDelaySeconds: 150
          timeoutSeconds: 4
          failureThreshold: 3
        resources:
          limits:
            memory: 1Gi
            cpu: 1000m
          requests:
            memory: 512Mi
            cpu: 500m
        volumeMounts:
        - name: keycloak-data
          mountPath: /opt/keycloak/data
  volumeClaimTemplates:
  - metadata:
      name: keycloak-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi