apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  vault.hcl: |
    ui = true
    
    listener "tcp" {
      address = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8201"
      tls_disable = 1
    }
    
    storage "raft" {
      path = "/vault/data"
      node_id = "${VAULT_RAFT_NODE_ID}"
      retry_join {
        leader_api_addr = "http://vault-0.vault-headless:8200"
      }
      retry_join {
        leader_api_addr = "http://vault-1.vault-headless:8200"
      }
      retry_join {
        leader_api_addr = "http://vault-2.vault-headless:8200"
      }
    }
    
    service_registration "kubernetes" {
      namespace = "${VAULT_K8S_NAMESPACE}"
      pod_name = "${VAULT_RAFT_NODE_ID}"
    }
    
    api_addr = "http://${POD_IP}:8200"
    cluster_addr = "http://${POD_IP}:8201"
    
    # Enable telemetry for monitoring
    telemetry {
      prometheus_retention_time = "30s"
      disable_hostname = true
    }